---
- name: Install dependencies
  apt:
    name: [python3, python3-pip]
    state: present
    update_cache: yes

- name: Copy Flask app
  copy:
    src: app.py
    dest: /opt/app/app.py
    mode: 0755

- name: Install Flask
  pip:
    name: flask
    executable: pip3

- name: Configure systemd service
  template:
    src: flask.service.j2
    dest: /etc/systemd/system/flask.service
  notify: restart flask
